

function color1(){
    let parrafo = document.getElementsByTagName("p")[0];
    let colores = ["red", "yellow", "blue", "green"];
    let i =  Math.floor(Math.random() * 4);
    parrafo.style.color=colores[i];
}


function color2(){
    let parrafo = document.getElementsByTagName("p")[1];
    let colores = ["red", "yellow", "blue", "green"];
    let i =  Math.floor(Math.random() * 4);
    parrafo.style.color=colores[i];
}


function color3(){
    let parrafo = document.getElementsByTagName("p")[2];
    let colores = ["red", "yellow", "blue", "green"];
    let i =  Math.floor(Math.random() * 4);
    parrafo.style.color=colores[i];
}