
function peque(){
    let parrafo = document.getElementsByTagName("p")[0];
    parrafo.style.fontSize="20px";
}


function medi(){
    let parrafo = document.getElementsByTagName("p")[0];
    parrafo.style.fontSize="40px";
}


function grand(){
    let parrafo = document.getElementsByTagName("p")[0];
    parrafo.style.fontSize="60px";
}

function negrita(){
    let parrafo = document.getElementsByTagName("p")[0];
    parrafo.style.fontWeight="bold";
}

function cursiva(){
    let parrafo = document.getElementsByTagName("p")[0];
    parrafo.style.fontStyle="italic";
}