function color1(){
    let parrafo = document.getElementsByTagName("p");

    for(let i = 0; i<parrafo.length; i++){
        parrafo[i].style.color="red";
    }
}

function color2(){
    let parrafo = document.getElementsByTagName("p");

    for(let i = 0; i<parrafo.length; i++){
        parrafo[i].style.color="green";
    }
}

function color3(){
    let parrafo = document.getElementsByTagName("p");

    for(let i = 0; i<parrafo.length; i++){
        parrafo[i].style.color="blue";
    }
}