
function visualizar1(){
    let parrafo = document.getElementById("uno");
        alert(parrafo.textContent);
}

function visualizar2(){
    let parrafo = document.getElementsByTagName("p");
        alert(parrafo[1].textContent);
}

function visualizar3(){
    let parrafo = document.getElementsByTagName("p");
        alert(parrafo[2].textContent);
}

function visualizar4(){
    let parrafo = document.getElementsByTagName("p");
        alert(parrafo[3].textContent);
}
